/* ---------------------------------------------------- +/

## Fixtures ##

Fill in the app with dummy data if database is empty.

/+ ---------------------------------------------------- */

// Insert fixture data here

/* Dictionaries: Data Fixtures */

if (Dicts.find().count() === 0) {
    var now = new Date().getTime();
    // sanidad
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'sanidad',
        slug: 'sanidad',
        description: 'El acceso a una sanidad pública y universal y de calidad es un requisito indispensable para la dignidad de las personas y es un factor esencial para garantizar la equidad y evitar la exclusión social de las personas y colectivos que viven en situación de especial vulnerabilidad. ',
        icon1: 'sanidad-01.svg',
        icon2: 'sanidad-02.svg',
        iconb1: 'sanidad-01.svg',
        iconb2: 'sanidad-02.svg',
        words: [
            'Acces.*salud',
            'Acces.*sistema.*sanitario',
            'Asegura.*salud',
            'Asegura.*sanitari',
            'Atención.*sanitaria',
            'Atención.*\bdependencia\b',
            'Ayuda.*\bdependencia\b',
            'Ayuda.*dependient',
            'Beneficiari.*salud',
            'Beneficiari.*sanidad',
            'Cartera.*básica.*prestaci',
            'Cartera.*básica.*servicios asistenciales',
            'Centro.*salud',
            'Cobertura.*sanitaria',
            'Concierto.*sanidad',
            'Concierto.*salud',
            'Convenio.*especial.*salud',
            'Convenio.*especial.*sanidad',
            'Copago.*sanitario',
            'Copago.*farmac',
            'Copago.*medic',
            'Copago.*sanitario',
            'Derecho.*protección.*salud',
            'Derecho.*salud',
            'Derecho.*sanidad',
            'Desnutri',
            '\bdependencia\b',
            'Determinante social.*salud',
            'Determinantes sociales.*salud',
            'Dispensa.*medicamento',
            'Dispensa.*fármaco',
            'Dispensa.*producto.*sanitari',
            'Drogodependencia',
            'Enfermedad.*colectivo.*excluido',
            'Enfermedad.*exclusión',
            'Enfermedad.*Declaración.*Obligatoria',
            'Exclusión.*sanitaria',
            'Externaliz.*sanidad',
            'Externaliz.*sistema sanitario',
            'Financia.*sanidad',
            'Financia.*salud',
            'Financia.*medicamento',
            'Financia.*fármaco',
            'Financia.*producto.*sanitario',
            'Gasto.*farmaceútico',
            'Gasto.*sanitario',
            'Gasto.*salud',
            'Gratuidad.*atención.*primaria',
            'Gratuidad.*medicamento',
            'Hábitos saludables',
            'Hepatitis C',
            'Inmigra.*salud',
            'Inmigra.*tarjeta.*sanitaria',
            'Malnutri',
            'Minoría.*étnic',
            'Modelo asistencial',
            'Pacto.*sanidad.*servicios sociales',
            'Persona[ s] mayor',
            'Población.*vulnerab.*salud',
            'Prescripción.*medicamento',
            'Prestac.*ortopréstica',
            'Prestac.*farmacéutica',
            'Privatiz.*sanidad',
            'Privatiz.*sistema.*sanitario',
            'Privatiz.*salud',
            'Protección.*salud',
            'Prostitución',
            '16\\W2012',
            'Recorte.*sanitari',
            'Reestructuración.*salud',
            'Reestructuración.*sanidad',
            'Reducción.*gasto.*salud',
            'Reducción.*gasto.*sanidad',
            'Salubridad',
            'Sanidad pública',
            'Sanidad.*universal',
            'Servicio.*asistencial',
            'Servicio.*sociosanitario',
            '\\WSIDA\\W',
            'Sistema sanitario',
            'Sistema Nacional de Salud',
            'Sostenib.*salud',
            'Sostenib.*sanidad',
            'Tarjeta.*sanitaria',
            'Trata de personas',
            'Tuberculosis',
            'Uso.*racional.*medicamento',
            '\\WVIH\\W',
            'Vulnerabilidad.*acceso.*salud',
            'Vulnerabilidad.*acceso.*sanidad ',
        ],
        lastUpdate: now,
    });
    // educacion
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'educación',
        slug: 'educacion',
        description: 'La educación es un factor que incide de forma determinante en la situación de vulnerabilidad en la que se encuentran muchas familias en España y en sus posibilidades de superarla. Una educación pública equitativa inclusiva y de calidad es esencial para acabar con las desigualdades sociales.',
        icon1: 'educacion-01.svg',
        icon2: 'educacion-02.svg',
        iconb1: 'educacion-01.svg',
        iconb2: 'educacion-02.svg',
        words: [
            'Abandono.*escolar',
            'Absentismo.*escolar',
            'Acceso.*educación',
            'Acoso.*escolar',
            'Alfabetiza',
            'Apoyo.*escolar',
            'Aula[ s] mentor',
            '\\Wbeca\\W',
            'Brecha digital',
            'Calidad.*Educa',
            'Centro.*educación infantil',
            'Centro[ s] escolar',
            'Derecho.*educación',
            'Determinante social.*educación',
            'Determinantes sociales.*educación',
            'Educación de calle',
            'Educación.*discapaci',
            'Educación.*financier',
            'Educación formal',
            'Educación.*obligatoria',
            'Educación infantil',
            'Educación básica',
            'Educación pública',
            'Educación.*universal',
            'Educador',
            'Escolariza',
            'Escuela.*infantil',
            'Escuela.*taller',
            'Exclu.*educa',
            'Extraescolar',
            'Financia.*educa',
            'Formación básica',
            'Formación profesional',
            'Fracaso.*escolar',
            'Gasto.*educativo',
            'Gasto.*educación',
            'Gasto por alumno',
            'Gratuidad.*educación',
            'Guardería',
            'Inclusión.*educa',
            'Interculturalidad.*educación',
            'Interculturalidad.*formación',
            'Interculturalidad.*profesor',
            'Libro[ s] de texto',
            '8\\W2013\\W',
            'Ley Wert',
            'LOMCE',
            'Material didáctico',
            'Material escolar',
            'Necesidad.*educativ.*especial',
            'Preescolar',
            'Privatiz.*educa',
            'ratio.*alumno',
            'Recorte.*educación',
            'Refuerzo.*profesor',
            'Segrega.*educación',
            'Segrega.*educativ',
            'Tasa.*escolar',
            'Tecnología.*educación',
            'Transporte.*escolar',
        ],
        lastUpdate: now,
    });
    // vivienda
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'vivienda',
        slug: 'vivienda',
        description: 'El acceso a una vivienda es una necesidad básica imprescindible para vivir con dignidad y seguridad. La ausencia de ésta afecta al desarrollo pleno de los derechos de las personas y las necesidades de las familias.',
        icon1: 'vivienda-01.svg',
        icon2: 'vivienda-02.svg',
        iconb1: 'vivienda-01.svg',
        iconb2: 'vivienda-02.svg',
        words: [
            'Acceso.*banda ancha.*vivienda',
            'Acceso.*banda ancha.*casa',
            'Acceso.*vivienda',
            'Acceso.*casa',
            'Acceso.*vivienda.*violencia de género',
            'Acceso.*casa.*violencia de género ',
            'Alojamiento.*alternativo',
            'Asentamiento.*irregular',
            'Asentamiento.*marginal',
            'Ayuda.*alquiler',
            'Ayuda.*vivienda',
            'Ayuda.*casa',
            'Barrio.*pobreza',
            'Barrio.*chabol',
            'Barrio.*segrega',
            'Barrio.*marginal',
            'Barrio.*vulnerable',
            'Bono social.*electricidad',
            'Bono social.*gas',
            'Casa.*vac’a',
            'Casa.*ocupada',
            'Chabol',
            'Dación en pago',
            'Derecho.*vivienda',
            'Derecho.*casa',
            'Desahuc',
            'Desaloj',
            'Ejecu.*hipoteca',
            'Emergencia habitacional',
            'Exclusión.*residencial',
            'Factura energética',
            'Factura.*energía',
            'Factura.*luz',
            'Familia.*sobreendeudada.*vivienda',
            'Familia.*sobreendeudada.*casa',
            'Fondo.*\bsocial\b.*vivienda',
            'Fondo.*\bsocial\b.*casa',
            'Garantía.*hipotec',
            'Gentrificación',
            'Habilidad.*residencial',
            'Habilidad.*conviv',
            'Habitabilidad',
            'Hacina',
            'Impag.*hipoteca',
            'Indigen',
            'Infravivienda',
            'Inmueble.*desocupa',
            'Mendig',
            'Mendicidad',
            'Ocupaci—n.*vivienda',
            'Ocupaci—n.*casa',
            '\\WPAH\\W',
            'Plataforma.*Afectado.*Hipoteca',
            'Persona.*sin hogar',
            'Persona.*sin casa',
            'Petición.*desaloj',
            'Piso.*inserción social',
            'Piso.*tutelado',
            'Plan.*Estat.*Vivienda',
            'Plan.*ayuda.*alquiler',
            'Pobreza.*poblado',
            'Pobreza energética',
            'Pobreza habitacional',
            'Precariedad.*habitac',
            'Programa.*ayuda.*alquiler',
            'Realoj',
            'Rehabilita.*vivienda',
            'Rehabilita.*casa',
            'Renta.*básica.*emancipa',
            'Salubridad',
            'Saneamiento.*básico',
            'Segrega.*residen',
            'Sin hogar',
            'Sin techo',
            'Sinhogarismo',
            'Tarifa.*luz.*pobre',
            'Tarifa.*eléctrica.*pobre',
            'Tarifa social',
            'Tarifa.*\bsocial\b.*electricidad',
            'Tarifa.*\bsocial\b.*luz',
            'Tarifa.*\bsocial\b.*gas',
            'Unidad.*convivencia',
            'Vivienda.*digna',
            'Vivienda.*protección oficial',
            'Vivienda[ s] normalizada',
            'Vivienda.*\bsocial\b',
            'Vivienda.*vacía',
            'Vivienda.*ocupada',
            '\\WVPO\\W ',
        ],
        lastUpdate: now,
    });
    // renta
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'renta',
        slug: 'renta',
        description: 'Un sistema de prestaciones económicas dignas y adecuadas a las necesidades de las personas y las familias que garantice un nivel mínimo de renta en el acceso a bienes y servicios elementales es una piedra angular para la lucha contra la pobreza y la exclusión.',
        icon1: 'renta-01.svg',
        icon2: 'renta-02.svg',
        iconb1: 'renta-01.svg',
        iconb2: 'renta-02.svg',
        words: [
            'Ayuda.*depend',
            'Ayuda.*\bsocial\b',
            'Ayuda.*emergencia ',
            'Ayuda.*económica.*violencia de género',
            'Cohesión.*\bsocial\b',
            'Desgrava.*fiscal',
            'Exención.*fiscal',
            'Equidad.*\bsocial\b',
            'Emergencia.*\bsocial\b',
            'Ingreso.*Mínimo.*Solidaridad',
            '\\WIMS\\W',
            'Pensión',
            'Pensión.*fallec',
            'Pensión.*invalidez',
            'Pensión.*inválid',
            'Pensión.*contributiva',
            'Pensión.*jubil',
            'Pensión.*vejez',
            'Prestación.*desemple',
            'Prestación.*parad[oa]',
            'Prestación.*contributiva',
            'Prestación.*incapacidad',
            'Prestación.*invalidez',
            'Prestación.*inválid',
            'Prestación.*jubila',
            'Prestación pública',
            'Prestaciones públicas',
            'Renta.*activa.*inserción.*violencia de género',
            'Renta[ s] básica',
            'Renta.*básica.*universal',
            'Renta.*activa.*inserción',
            'Renta.*agraria',
            'Renta.*inserción ',
            'Renta.*condicionada',
            'Renta.*garantizada.*ciudadan',
            'Renta.*mínima',
            '\\WRMI\\W',
            'Salario social',
            'Seguro.*desemple',
            'Seguro.*parad',
            'Seguro.*Obligatorio.*Vejez',
            'Seguro.*Obligatorio.*Invalidez',
            '\\WSOVI\\W',
            'Subsidio.*desempleo',
            'Subsidio.*agrari',
        ],
        lastUpdate: now,
    });
    // empleo
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'empleo',
        slug: 'empleo',
        description: 'El trabajo siempre han sido un elemento crucial para la cohesión y la inclusión social, pero hoy tener empleo o no tenerlo ya no es el único elemento diferencial entre la inclusión y la exclusión. La precariedad en el empleo genera, igualmente, exclusión y pobreza.',
        icon1: 'empleo-01.svg',
        icon2: 'empleo-02.svg',
        iconb1: 'empleo-01.svg',
        iconb2: 'empleo-02.svg',
        words: [
            'Acompaña.*laboral',
            'Agencia.*colocación',
            'Ajuste.*salari',
            'Apoyo.*depend',
            'Apoyo.*diversifica.*profesional',
            'Autoempleo ',
            'Bonifica.*contrata',
            'Brecha.*salari',
            'Centro.*educación infantil',
            'Centro[ s] de día',
            'Certificado.*profesionalidad',
            'Concilia.*familia',
            'Concilia.*laboral',
            'Concilia.*mujer',
            'Congela.*salari',
            'Contención.*salari',
            'Contrata.*discapaci',
            'Crea.*empleo',
            'Crea.*trabajo',
            'Cualificación.*laboral',
            'Cualificación.*profesional',
            'De m‡s edad',
            'Desemple',
            'Destru.*empleo',
            'Destru.*trabajo',
            'Devalua.*salari',
            'Discapaci.*empleo',
            'Discapaci.*trabaj',
            'Disminución.*salari',
            'Empleabilidad',
            'Empleo.*joven',
            'Empleo.*calidad',
            'Empleo.*decente',
            'Empleo.*digno',
            'Empleo.*estable',
            'Empleo.*inclusivo',
            'Empleo.*precario',
            'Empleo.*protegido',
            'Empleo.*rural',
            'Emprendedor',
            'Emprendimiento',
            'Emprendimiento.*\bsocial\b',
            'Emprendedor.*\bsocial\b',
            'Empresa.*Inserción',
            'Empresa[ s] social',
            'Envejecimiento activo',
            '\\WERE\\W',
            'Escuela.*infantil ',
            'Expediente.*Regulación.*Empleo',
            'Experiencia laboral',
            'Experiencia profesional',
            'Flexibili.*horario',
            'Flexibili.*laboral',
            'Flexiseguridad',
            'Formación.*empleo',
            'Formación.*empresarial',
            'Formación.*laboral',
            'Formación profesional',
            'Garantía.*juvenil',
            'Gasto laboral',
            'Guardería',
            'Hijo[ s] a cargo',
            'Incentivo.*empleo',
            '\\WINEM\\W ',
            'Inserción.*profesional',
            'Inserción.*laboral',
            'Inserción.*laboral.*violencia de género',
            'Inserción.*sociolaboral',
            'Intermediación.*laboral ',
            'Laboral.*inclusión',
            'Mayor.*45 años',
            'Microcrédito',
            'Microemprend',
            'Micropréstamo',
            'Moderación.*salari',
            'Oportunidad.*empleo',
            'Oportunidad.*trabajo',
            'Parad[oa]',
            'Pequeñ[oa].*emprendedor',
            'Permiso.*acogimiento',
            'Permiso.*adopción',
            'Permiso.*maternidad',
            'Persona.*desemplead',
            'Persona.*parada',
            'Plan.*\\WPREPARA\\W ',
            'Pobreza.*empleado',
            'Pobreza.*trabajador',
            'Política.*activa.*.*empleo',
            'Política.*activa.*trabajo',
            'Portal único.*empleo',
            'Precari.*laboral',
            'Programa.*experimental.*empleo',
            'Redu.*salari',
            'Recualificación',
            'Regulación.*pr‡ctica.*laboral',
            'Salario.*Digno',
            'Salario.*Máximo',
            'Salario.*Mínimo',
            'Salario.*Mínimo.*Interprofesional',
            'Salario.*desigualdad',
            'Salario.*poder adquisitivo',
            'Servicio Público.*Empleo',
            '\\WSMI\\W ',
            '\\WSPEE\\W ',
            'Start Up',
            'Taller.*empleo',
            'Taller.*trabajo',
            'Tasa.*desempleo',
            'Tasa.*paro',
            'Trabajador.*pobre',
            'Trabajo.*calidad',
            'Trabajo.*decente',
            'Trabajo.*digno',
            'Trabajo.*inclusivo',
            'Trabajo.*precario',
            'Trabajo.*privado',
            'Trabajo.*público',
            'Yacimiento.*empleo',
        ],
        lastUpdate: now,
    });
    // infancia
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'infancia',
        slug: 'infancia',
        description: 'Todo compromiso de reducción de la pobreza y de promoción y defensa de los derechos de la infancia debe tener en cuenta la educación, salud y alimentación, así como otras actividades que fomenten su desarrollo pleno y el de sus familias.',
        icon1: 'infancia-01.svg',
        icon2: 'infancia-02.svg',
        iconb1: 'infancia-01.svg',
        iconb2: 'infancia-02.svg',
        words: [
            'Abandono.*escolar',
            'Absentismo.*escolar',
            'Abuso infantil',
            'Abuso.*menor',
            'Acceso.*banda ancha.*familia',
            'Acceso.*banda ancha.*hogar',
            'Acceso.*banda ancha.*casa',
            'Acceso.*internet.*familia',
            'Acceso.*internet.*hogar',
            'Acceso.*internet.*casa',
            'Acceso.*red.*familia',
            'Acceso.*red.*hogar',
            'Acceso.*red.*casa',
            'Acceso.*educación',
            'Acceso.*vivienda.*violencia de género',
            'Acceso.*infantil.*red',
            'Acceso.*infantil.*internet',
            'Acogimiento',
            'Acogida.*menor',
            'Acoso.*escolar',
            'Adolescen',
            'Adopción.*menor',
            'Adopción.*infantil',
            'Adopción.*internacional',
            'Adopciones.*internacionales',
            'Alojamiento.*alternativo',
            'Apoyo.*escolar',
            '\\WAROPE\\W.*familia',
            '\\WAROPE\\W.*infancia',
            'Asentamiento.*marginal',
            'Asistencia social.*integral.*menor',
            'Asistencia social.*integral.*violencia de género',
            'Asistencia.*\bsocial\b.*menor',
            'Asistencia.*\bsocial\b.*violencia de género',
            'Atención.*temprana',
            'Aula.*taller',
            'Ayuda.*alquiler',
            'Ayuda.*alquiler.*familia',
            'Ayuda.*alquiler.*infancia',
            'Ayuda.*familia',
            'Ayuda.*vivienda.*familia',
            'Ayuda.*casa.*familia',
            'Ayuda.*vivienda.*infancia',
            'Ayuda.*económica.*violencia de género',
            'Barrio.*vulnerable',
            '\\WBeca\\W',
            'Beca.*comedor',
            'Beca.*educación infantil',
            'Beca.*educación primaria',
            'Beca.*educa',
            'Beca.*estudio',
            'Beca.*libro',
            'Bienestar.*infantil',
            'Bono.*\bsocial\b.*electricidad',
            'Bon.*\bsocial\b.*luz',
            'Bono.*\bsocial\b.*gas',
            'Casa.*pobre',
            'Castigo.*físico.*infancia',
            'Castigo.*físico.*menor',
            'Centro.*educación infantil',
            'Chabol',
            'Concilia.*familia',
            'Concilia.*laboral',
            'Convención.*infancia',
            'Convivencia.*familia',
            'Cotutoría.*infancia',
            'Custodia.*hijo',
            'Dación en pago.*familia',
            'Derecho.*educación',
            'Derecho.*salud.*familia',
            'Derecho.*salud.*infancia',
            'Derecho.*salud.*menor',
            'Derecho.*salud.*niñ[oa]',
            'Desahuci.*familia',
            'Deshauci.*infancia',
            'Deshauci.*menor',
            'Desigualdad.*género.*infancia',
            'Discapaci.*infancia',
            'Educación.*calidad',
            'Educación.*calle',
            'Educación.*especial',
            'Educación.*financiera',
            'Educación.*gratuita',
            'Educación.*formal',
            'Educación.*obligatoria',
            'Educación.*pública',
            'Educación.*infantil',
            'Educación primaria',
            'Educador',
            'Emergencia.*habitacional.*infancia',
            'Emergencia.*\bsocial\b.*infancia',
            'Entorno.*\bsocial\b.*riesgo',
            'Equidad.*infancia',
            'Escolar',
            'Escolariza.*externa',
            'Escuela.*infantil',
            'Escuela.*taller',
            'Estrategia.*inclusión.*gitan',
            'Evalua.*infancia',
            'Exclusión.*educa',
            'Exclusión.*residencial',
            'Exclusión.*\bsocial\b',
            'Familia.*acogedora',
            'Familia.*acogida',
            'Familia.*monoparental',
            'Familia.*numerosa',
            'Familia.*pobreza',
            'Familia.*tradicional',
            'Familia.*víctima',
            'Finaliza.*estudio',
            'Flexibilidad.*horario',
            'Fondo.*ayuda.*desfavorecidos',
            'Fondo.*\bsocial\b.*vivienda',
            'Formación básica',
            'Fracaso.*escolar',
            'Garantía.*hipoteca.*familia',
            'Garantía.*hipoteca.*infancia',
            'Garantía.*juvenil',
            'Gasto.*educa',
            'Gasto.*alumno',
            'Gratui.*educación',
            'Guardería',
            'Habilidad.*residencial',
            'Habilidad.*convivencia',
            'Habitabilidad',
            'Hacina',
            'Hijo.*cargo',
            'Hogar.*pobre',
            'Hogar.*sin.*ingreso',
            'Igualdad.*género.*infancia',
            'Impago.*hipoteca.*familia',
            'Impago.*hipoteca.*infancia',
            'Inclusión.*educa',
            'Infancia',
            'Infancia.*violencia de género',
            'Infantil',
            'Infravivienda',
            'Ingreso.*familia',
            'Inserción.*laboral.*violencia de género',
            'Intercultural.*educa',
            'Intercultural.*formación',
            'Intercultural.*profesor',
            'Intervención.*famili',
            'Inversión.*infancia',
            'Itinerario.*formativo',
            'Libro[ s] de texto',
            '\\WLOMCE\\W ',
            'Malnutri',
            'Malnutri.*infan',
            'Maltrat',
            'Maltrat.*infan',
            'Material didáctico',
            'Menor de edad',
            'Menores de edad',
            'Menor.*violencia de género',
            'Menor.*riesgo',
            'Menor.*exclusión.*\bsocial\b',
            'Menores.*exclusión.*\bsocial\b',
            'Menor.*exclu',
            'Menor.*infractor',
            'Menor no acompañado',
            'Menores no acompañados',
            'Menor.*víctima',
            'Monoparental',
            'Mujer.*rural',
            'Necesidad.*educativa.*especial',
            'Niñ[oa]',
            'Niñ[oa].*violencia de género',
            'Ocio.*infancia',
            'Pacto.*Estado.*infancia',
            'Pacto.*sanidad.*servicios sociales',
            'Padre',
            'Padre.*divorciado',
            'Padre.*separado',
            'Parentalidad',
            'Parentalidad.*positiva',
            'Participa.*infancia',
            'Participa.*niñ[oa]',
            'Participa.*infantil',
            'Participa.*menor',
            'Patria potestad',
            'Pensión.*alimenticia.*violencia de género',
            'Permiso.*acogimiento',
            'Permiso.*adopción',
            'Permiso.*maternidad',
            'Persona.*situación.*exclusión social',
            'Persona.*situación.*pobreza',
            'Persona.* situación.*irregular',
            'Piso.*inserción social.*familia',
            'Piso.*inserción social.*infancia',
            'Piso.*inserción social.*menor',
            'Plan.*concertado.*prestaci.*básica',
            'Plaza.*escuela.*infantil',
            'Pobreza energética',
            'Pobreza.*infancia',
            'Pobreza.*familia',
            'Pobreza.*menor',
            'Pobreza infantil',
            'Prestaci.*hijo',
            'Prestaci.*niño',
            'Prestación.*hijo a cargo',
            'Presupuesto.*infancia',
            'Prevención.*adicc.*adolescente',
            'Prevención.*adicc.*jóvenes',
            'Prevención.*adicc.*menor',
            'Privación.*infancia',
            'Privación.*familia',
            'Privación.*menor',
            'Privación material.*severa.*familia',
            'Privación material.*severa.*infancia',
            'Privación material severa.*menor',
            'Ratio.*alumno.*profesor',
            'Realojo',
            'Renta activa.*inserción.*violencia de género',
            'Riesgo.*pobreza.*familia',
            'Riesgo.*pobreza.*infancia',
            'Riesgo.*pobreza.*menor',
            'Salud.*infantil',
            'Servicio.*\bsocial\b.*infancia',
            'Sin hogar.*infancia',
            'Sinhogarismo.*infancia',
            'Tarifa.*luz.*pobreza',
            'Tarifa eléctrica.*pobreza',
            'Tarifa.*electricidad.*pobreza',
            'Tarifa social',
            'Tarifa.*\bsocial\b.*electricidad',
            'Tarifa.*\bsocial\b.*luz',
            'Tarifa.*\bsocial\b.*gas',
            'Tasa.*escolar.*infancia',
            'Tasa.*escolar.*menor',
            'Tipo.*familia',
            'Transporte.*escolar',
            'Tutela.*infancia',
            'Unidad.*convivencia',
            'Víctima.*violencia de género',
            'Violencia.*contra.*infancia',
            'Violencia.*pareja',
            'Violencia doméstica',
            'Violencia.*hogar',
            'Vivienda.*digna',
            'Vivienda.*normalizada',
            'Vivienda.*protección oficial.*infancia',
            'Vivienda.*\bsocial\b.*infancia',
            'VPO.*infancia',
        ],
        lastUpdate: now,
    });
    // inmigración y extranjería
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'inmigración y extranjería',
        slug: 'inmigracion-y-extranjeria',
        description: 'La intensidad de los flujos migratorios se ha acelerado en la última década y se utilizan vías cada vez más peligrosas. Atajar la vulneración de los derechos fundamentales de las personas migrantes en nuestro país es imprescindible para evitar que se encuentren en situación de exclusión social en España. Realidades como los CIE o las redadas policiales por perfil racial vulneran el derecho a migrar.',
        icon1: 'extranjera-01.svg',
        icon2: 'extranjera-02.svg',
        iconb1: 'extranjera-01.svg',
        iconb2: 'extranjera-02.svg',
        words: [
            'Acceso.*sistema.*sanitario',
            'Acceso.*sanidad',
            'Acceso.*servicio.*sanitario',
            '\\WACNUR\\W',
            'Adqui.*nacionalidad',
            'Apartheid.*sanitario',
            'Asalto.*Ceuta',
            'Asalto.*Melilla',
            'Asil',
            'Barrio.*chabol',
            'Barrio.*segregado',
            'Cayuco',
            'Chabol',
            'Centro.*Estancia.*Temporal',
            'Centro.*Internamiento.*Extranjero',
            'Centro.*Participación.*Integración',
            '\\WCEPI\\W',
            '\\WCETI\\W',
            '\\WCIE\\W',
            'Concertina',
            'Convenio.*189',
            'Étnic.*identificación',
            'étni.*identificación',
            'DDHH',
            'DD\\WHH',
            'Delito.*odio',
            'Deporta',
            'Derechos humanos',
            'Devolución.*caliente',
            'Discurso.*odio',
            'Enfermedad.*importa',
            'Exclusión.*sanitari',
            'Expulsión',
            'Expulsa',
            'Extradi',
            'Extranj',
            'Frontex',
            'Hate speech',
            'Identificación.*policía',
            'Indentificaciones.*policial',
            'Indocumentado',
            'Inmigr',
            'Inmigr.*salud ',
            'Inmigr.*irregular',
            'Inmigr.*ilegal',
            'Inmigr.*tarjeta.*sanitaria',
            'Interculturalidad.*educación',
            'Interculturalidad.*formación',
            'Interculturalidad.*profesorado ',
            'Ley.*Extranjería',
            '4\\W2000',
            'Menor.*acompañado',
            'Migra',
            'Mujer.*extranjer.*violencia de género',
            'Obten.*nacionalidad',
            'Patera',
            'Permiso.*residencia',
            'Permiso.*trabajo',
            'Población.*ruman',
            'Racismo',
            'Racist',
            '557\\W2011',
            '16\\W2012',
            'Redada',
            'Refugi',
            'Repatria',
            'Retorno.*inmigr',
            'Romaní',
            'Ruman',
            'Segrega',
            'Segrega.*educación',
            'Segrega.*sistema educativo',
            'Segrega.*residenc',
            '\\WSIDA\\W',
            'Sin papeles',
            'Situación.*irregular',
            'Tarjeta.*residencia',
            'Tarjeta sanitaria.*inmigr',
            'Tarjeta sanitaria.*extranjer',
            'Trabajador.*doméstic',
            'Trabajador.*hogar',
            'Trámite.*nacionalidad',
            'Trata de personas',
            'Tuberculosis',
            'Valla.*Ceuta',
            'Valla.*Melilla',
            '\\WVIH\\W',
            'Violencia.*género.*irregular',
            'Violencia.*género.*ilegal',
            'Visado.*inmigra',
            'Xenofobia',
            'Xenófobo',
        ],
        lastUpdate: now,
    });
    // personas sin hogar
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'personas sin hogar',
        slug: 'personas-sin-hogar',
        description: 'Las personas sin hogar se encuentran en una situación extrema de vulnerabilidad y exclusión social. Estas personas están en un proceso de pérdida del nicho social, afectivo y personal que afecta directamente a su desarrollo humano y requiere de políticas específicas para reducir su situación de vulnerabilidad.',
        icon1: 'sintecho-01.svg',
        icon2: 'sintecho-02.svg',
        iconb1: 'sintecho-01.svg',
        iconb2: 'sintecho-02.svg',
        words: [
            'Albergue.*hogar',
            'Alcohol.*hogar',
            'Alojamiento.*autonomía',
            'Alojamiento.*alternativo',
            'Alojamiento.*emergencia',
            'Alojamiento.*temporal',
            'Alojamiento.*transitorio',
            'Asentamiento.*marginal',
            'Asentamiento.*chabol',
            'Barrio.*chabol',
            'Barrio.*segrega.*hogar',
            'Campaña.*frío',
            'Campaña.*calor.*hogar',
            'Casa.*Acogida',
            'Centro.*Acogida',
            'Centro.*baja exigencia',
            'Centro[ s] de día',
            'Chabol',
            'Colectivo.*excluido',
            'Colectivo.*margi',
            'Comedor.*\bsocial\b',
            'Derecho.*casa',
            'Derecho.*vivienda',
            'Derecho.*hogar',
            'Derecho.*techo',
            'Desprotección social.*hogar',
            'Drogodepend.*hogar',
            'Ending.*Homelessness',
            'Ending.*Home',
            'Emergencia.*habit.*hogar',
            'Emergencia.*\bsocial\b.*hogar',
            'Equipo.*calle',
            'Estrategia.*sinhogarismo',
            'European.*Federation.*Homeless',
            'Exclusión.*residenc',
            'Exclusión.*\bsocial\b.*hogar',
            '\\WFEANTSA\\W',
            '\\WFEPSH\\W',
            'Habitabilidad.*hogar',
            'Hogar',
            'Hogar.*comunitario',
            'Homeless',
            'Homelessness',
            'Hotel.*\bsocial\b',
            'Housing.*first',
            'Housing.*led',
            'Indigencia',
            'Indigente',
            'Infravivienda',
            'Mendicidad',
            'Mendigo',
            'Mini.*residencia',
            'Pensión.*\bsocial\b',
            'Persona.*situación.*calle',
            'Persona.*situación.*hogar',
            'Persona.*exclusión social.*hogar',
            'Persona.*situación de pobreza.*hogar',
            'Persona.*hogar',
            'Piso.*acompa–amiento',
            'Piso.*compartido',
            'Piso.*apoyo',
            'Piso.*tutelado',
            'Plan.*Nacional.*Inclusi—n Social',
            'Poblaci—n.*exclu',
            'Poblado.*margi',
            'Pobreza.*habitacional',
            'Precariedad.*habitacional',
            'Recurso.*residencial',
            'Residencia.*comunitaria',
            'Residencia.*exclusi—n',
            'Residencia[ s] social ',
            'Salubridad.*hogar',
            'Salud.*mental.*hogar',
            'Salud.*mental.*exclu',
            'SAMUR.*\bsocial\b',
            'SAMUR.*Salud.*Mental',
            'Segrega.*residencial.*hogar',
            'Sin hogar',
            'Sinhogar',
            'Sin techo',
            'Sinhogarismo',
            'Sin hogarismo',
            'Situaci—n.*calle',
            'Trabajo.*calle',
            'Transeœnte.*hogar',
            'Vagabundo',
            'Vivienda.*compartida',
            'Vivienda.*apoyo',
            'Vivienda.*tutelada',
        ],
        lastUpdate: now,
    });
    // diversidad funcional
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'diversidad funcional',
        slug: 'diversidad-funcional',
        description: 'Las personas con discapacidad o diversidad funcional constituyen uno de los grupos con mayor discriminación en cuanto a accesibilidad, empleo, educación e igualdad de derechos, siendo una prioridad para cualquier estrategia de inclusión de colectivos vulnerables.',
        icon1: 'diversidad-01.svg',
        icon2: 'diversidad-02.svg',
        iconb1: 'diversidad-01.svg',
        iconb2: 'diversidad-02.svg',
        words: [
            'Atención.*domicil',
            'Atención.*\bdependencia\b',
            'Ayuda.*\bdependencia\b',
            'Ayuda.*dependient',
            'Apoyo.*\bdependencia\b',
            'Apoyo.*dependient',
            'Centro.*ocupacional',
            'Colectivo.*exclu',
            'Colectivo.*margin',
            'Discapaci',
            'Discapaci.*empleo',
            'Discapaci.*trabaj',
            'Discapaci.*f’sica',
            'Discapaci.*mental',
            'Diversidad.*funcional',
            'Educación.*discapaci',
            'Enfermedad.*discapaci',
            'Financia.*depend',
            'Grado.*incapacidad',
            'Grado.*invalid',
            'Invalid',
            'Ley.*\bdependencia\b',
            'Ley.*Integración.*Minusvál',
            '\\WLISMI\\W',
            'Minusval',
            'Movilidad.*reducida',
            'Pensión.*incapaci',
            'Pensión.*invalid',
            'Persona.*minusválida',
            'Persona.*discapaci',
            'Persona.*movilidad.*reducida',
            'Plan.*Inclusión Social',
            'Población.*exclu',
            'Recorte.*\bdependencia\b',
            'Riesgo.*pobreza.*discapaci',
            'Salud mental.*discapaci',
        ],
        lastUpdate: now,
    });
    // mayores
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'mayores',
        slug: 'mayores',
        description: 'La atención a la salud física y mental de las personas mayores y sus vínculos afectivos hacen que mejore su calidad de vida, enriqueciendo al mismo tiempo al conjunto de la sociedad. Las  prestaciones por parte de las Administraciones Públicas son esenciales para el desarrollo de estas medidas.',
        icon1: 'mayores-01.svg',
        icon2: 'mayores-02.svg',
        iconb1: 'mayores-01.svg',
        iconb2: 'mayores-02.svg',
        words: [
            'Abuel.*golondrina',
            'Residencia.*mayor.*violencia de género',
            'Aislamiento.*anciano',
            'Aislamiento.*persona mayor',
            'Aislamiento.*tercera edad',
            'Alzheimer',
            'Ancian[oa]',
            'Ancian.*violencia de género',
            'Atención.*domicil',
            'Autonomía personal',
            'Centro[ s] de día',
            'Consejo Estatal.*Personas Mayores',
            'Convivencia.*intergeneracional',
            'Convivencia.*inter.*generacional',
            'Coste.*sani.*persona mayor',
            'Coste.*sani*personas mayores',
            'Demencia',
            '\bDependencia\b',
            'Desprotección.*anciano',
            'Desprotección.*persona.*mayor',
            'Desprotección.*tercera edad',
            'Distanciamiento.*intergeneracional',
            'Distanciamiento.*inter.*generacional',
            'Edadismo',
            'Migr.*mayor ',
            'Migr.*tercera edad',
            'Enfermedad.*mayor',
            'Enfermedad.*depend',
            'Enfermedad.*ancian[oa]',
            'Envejec',
            'Envejecimiento activo',
            'Exclu.*\bsocial\b.*ancian[oa]',
            'Exclu.*\bsocial\b.*persona[ s] mayor',
            'Exclu.*\bsocial\b.*tercera edad',
            'Grado.*incapacidad',
            'Grado.*invalidez',
            'Hogar.*persona.*mayor',
            '\\WIMSERSO\\W',
            'Instituto.*Mayor.*Servicios Sociales',
            'Intergeneracional',
            'Inter.*generacional',
            'Invalidez',
            'Jubilad[oa]',
            'Ley.*\bdependencia\b',
            'Mal.*trato.*ancian',
            'Maltrat.*ancian',
            'Mal.*trato.*persona.*mayor',
            'Maltrat.*ancian',
            'Mal.*trato.*tercera edad',
            'Maltrat.*tercera edad',
            'Mayor.*violencia de género',
            'Pensión.*incapacidad',
            'Pensión.*fallecimiento',
            'Pensión.*invalidez',
            'Pensión.*Jubilación',
            'Pensión.*vejez',
            'Pensión',
            'Pensiones',
            'Persona.*situación.*\bdependencia\b',
            'Persona.*mayor',
            'Piso.*tutelado',
            'Plan Nacional.*inclusión.*\bsocial\b',
            'Población.*exclu',
            'Pobreza energética.*ancian[oa]',
            'Pobreza energética.*persona.*mayor',
            'Pobreza energética.*tercera edad',
            'Prestación.*incapacidad',
            'Prestación.*invalidez',
            'Prestación.*jubilación',
            'Programa.*Atención.*Persona.* Mayor',
            'Residencia.*mayor',
            'Residencia.*Tercera Edad',
            'Riesgo.*pobreza.*tercera edad',
            'Riesgo.*pobreza.*ancian[oa]',
            '\\WSAD\\W',
            'Seguro.*Vejez ',
            'Seguro.*Invalidez',
            'Senectud',
            'Senior',
            'Servicio.*Ayuda.*Domicilio',
            'Servicio.*Ayuda.*Domicilio.*Persona.*Mayor',
            'Servicio.*Ayuda.*Domicilio.*Persona.*Tercera Edad',
            'Servicio.*teleasistencia',
            'Servicio.*Tele asistencia',
            'Servicio.*Ayuda.*Domicilio',
            'Soledad.*ancian[oa]',
            'Soledad.*persona.*mayor',
            'Soledad.*tercera edad',
            'Solidaridad intergeneracional',
            '\\WSOVI\\W',
            'Subsidio.*migra',
            'Tercera edad',
            'Tercera edad.*violencia de género',
            'Vejez',
            'Vivienda.*compartida.*ancian',
            'Vivienda.*compartida.*persona.*mayor',
            'Vivienda.*compartida.*tercera edad',
            'Vivienda.*tutelada',
        ],
        lastUpdate: now,
    });
    // dependencia
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'dependencia',
        slug: 'dependencia',
        description: 'Garantizar los derechos de las personas que, por razones derivadas de la edad, la enfermedad o la discapacidad, precisan de atención para realizar las actividades básicas de la vida diaria es imprescindible para evitar el riesgo de exclusión social.',
        icon1: 'dependencia-01.svg',
        icon2: 'dependencia-02.svg',
        iconb1: 'dependencia-01.svg',
        iconb2: 'dependencia-02.svg',
        words: [
            'Apoyo.*\bdependencia\b',
            'Apoyo.*dependient',
            'Atención.*domiciliaria',
            'Ayuda.*\bdependencia\b',
            'Ayuda.*dependient',
            'Autonomía personal',
            'Centro[ s] de día',
            'Colectivo.*exclu',
            'Colectivo.*margina',
            '\bdependencia\b',
            'Desprotección.*\bsocial\b',
            'Enfermedad.*\bdependencia\b',
            'Enfermedad.*mayor',
            'Envejecimiento activo',
            'Hogar.*persona.*mayor',
            'Intergeneracional.*\bdependencia\b',
            'Invalidez',
            'Ley.*\bdependencia\b',
            'Ley.*Integración Social.*Minusválido',
            '\\WLISMI\\W',
            'Mayor.*\bdependencia\b',
            'Persona.*discapacidad',
            'Persona.*situación.*\bdependencia\b',
            'Persona.*mayor.*\bdependencia\b',
            'Plan Nacional.*Inclusión Social',
            'Población.*exclu.*\bdependencia\b',
            'Riesgo.*pobreza.*\bdependencia\b',
            'Servicio.*Ayuda.*Domicilio',
            'Servicio Teleasistencia',
            'Servicio.*Tele asistencia',
            'Servicio.*Ayuda.*Domicilio',
            'Servicio.*Público.*Ayuda.*Domicilio',
            'Sistema.*Atención.*\bdependencia\b',
            'Solidaridad.*intergeneracional.*\bdependencia\b',
            'Tercera edad.*\bdependencia\b',
            'Vejez.*\bdependencia\b',
            '39\\W2006',
            'Prestación.*incapacidad',
            'Prestaciones.*incapacidad',
            'Prestación.*invalidez',
            'Prestaciones.*invalidez',

        ],
        lastUpdate: now,
    });
    // violencia de género
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'violencia de género',
        slug: 'violencia-de-genero',
        description: 'La violencia de género, ejercida en su mayoría contra las mujeres, es fruto de la situación de subordinación a la que la sociedad relega a la mujer, siendo la mayor desigualdad en cifras de la actualidad. Es necesario proteger los derechos de las víctimas de violencia de género, especialmente de mujeres y menores para alcanzar el desarrollo pleno de todas las personas pertenecientes a la sociedad.',
        icon1: 'genero-01.svg',
        icon2: 'genero-02.svg',
        iconb1: 'genero-01.svg',
        iconb2: 'genero-02.svg',
        words: [
            'Abuso.*género',
            'Abuso.*mujer',
            'Acceso.*vivienda.*violencia de género',
            'Asistencia jurídica.*violencia de género',
            'Asistencia.*\bsocial\b.*integral.*menor',
            'Asistencia.*\bsocial\b.*integral.*violencia de género',
            'Asistencia.*\bsocial\b.*menor',
            'Asistencia.*\bsocial\b.*violencia de género',
            'Ayuda.*económica.*.*violencia de género',
            'Desigualdad.*género.*violencia de género',
            'Desprotección.*\bsocial\b',
            'Empleo.*violencia de género',
            'Entorno.*familiar.*violencia de género',
            'Familia.*víctima.*género',
            'Infancia.*violencia de género',
            'Inserción.*laboral.*violencia de género',
            'Integridad física.*género',
            'Integridad moral.*género',
            'Ley.*Violencia de Género',
            '1\\W2004\\W',
            'Libertad.*sexual.*mujer',
            'Libertad.*sexual.*violencia de género',
            'Maltrat',
            'Maltrat.*violencia de género',
            'Maltrat.*pareja',
            'Mayor.*violencia de género',
            'Menor.*víctima',
            'Mujer.*extranjer.*violencia de género',
            'Mujer.*víctima',
            'Niñ[oa].*violencia de género',
            'Menor.*violencia de género',
            'Orden.*protección.*víctima.*genero',
            'Pensión.*alimenticia.*violencia de género',
            'Plan nacional.*acción.*inclusión social',
            'Plan.*igualdad',
            'Plan.*mujer.*oportunidad',
            'Privación.*libertad.*género',
            'Renta activa.*inserción.*violencia de género',
            'Salud.*física.*violencia de género',
            'Salud.*psicológica.*violencia de género',
            'Servicio 016',
            'Tercera edad.*violencia de género',
            'Trabajo.*violencia de género',
            'Víctima.*violencia de género',
            'Víctima.*mortal.*violencia de género',
            'Violencia de género',
            'Violencia de género.*irregular',
            'Violencia de género.*ilegal',
            'Violencia.*pareja',
            'Violencia doméstica',
            'Violencia.*hogar',
            'Violencia física.*género',
            'Violencia psicológica.*género',
        ],
        lastUpdate: now,
    });
    // población gitana
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'población gitana',
        slug: 'poblacion-gitana',
        description: 'La discriminación de la comunidad gitana, afectada por el rechazo, la marginación y/o la privación material, afecta a la garantía de sus derechos más fundamentales. Para reducir la brecha de la desigualdad se deben abordar sus necesidades específicas.',
        icon1: 'gitana-01.svg',
        icon2: 'gitana-02.svg',
        iconb1: 'gitana-01.svg',
        iconb2: 'gitana-02.svg',
        words: [
            'Abuso.*género',
            'Abuso.*mujer',
            'Acceso.*vivienda.*violencia de género',
            'Antigitanismo',
            'Anti.*gitan',
            'Asentamiento.*marginal',
            'Asistencia jurídica.*grat.*violencia de género',
            'Asistencia.*\bsocial\b.*integral.*menor',
            'Asistencia.*\bsocial\b.*integral.*violencia de género',
            'Ayuda.*económica.*violencia de género',
            'Barrio.*chabol',
            'Barrio.*segrega',
            'Barrio.*vulnerab',
            'Chabol',
            'Colectivo.*gitano',
            'Colectivo.*romaní',
            'Colectivo.*exclu',
            'Colectivo.*margi',
            'Comunidad.*gitan',
            'Consejo.*Pueblo Gitano',
            'Consejo.*Gitano',
            'Cultura.*gitan',
            'Delito.*odio',
            'Desigualdad de género',
            'Desigualdad.*género.*violencia',
            'Desprotección social',
            'Determinante.*\bsocial\b.*Educación',
            'Determinante.*\bsocial\b.*Salud',
            'Discriminación.*gitan',
            'Entorno.*famili.*violencia de género',
            'Entorno.*\bsocial\b.*riesgo',
            'Equidad.*Salud',
            'Estrategia.*inclusión social.*gitan',
            'Exclu.*\bsocial\b',
            'Familia.*víctima',
            'Gitan',
            'Gitanofobia',
            'Habitabilidad',
            'Hábito.*saludable',
            'Hate speech',
            'Inclusión social.*gitan',
            'Identidad.*cultura.*gitan',
            'Igualdad.*trato',
            'Infancia.*violencia de género',
            'Infravivienda',
            'Inserción.*laboral.*violencia de género',
            'Integridad física.*género',
            'Integridad moral.*género',
            'Interculturalidad.*educación',
            'Interculturalidad.*formación',
            'Interculturalidad.*profesor ',
            '1\\W2004\\W',
            'Ley.*Protección.*Violencia de Género',
            'Libertad sexual.*mujer',
            'Libertad sexual.*violencia de género',
            'Malnutri',
            'Maltrat',
            'Maltrat.*violencia de género',
            'Maltrato.*pareja',
            'Mayor.*violencia de género',
            'Menor.*víctima',
            'Minoría',
            'Minoría.*ƒtnica',
            'Minoría.*etnia',
            'Mujer.*gitana',
            'Mujer.*extranj.* violencia de género',
            'Mujer.*víctima',
            'Niñ[oa].*violencia de género',
            'Pension.*alimenticia.*violencia de género',
            'Plan nacional.*acción.*inclusión social',
            'Plan nacional.*gitan',
            'Plan.*igualdad.*oportunidad.*mujer',
            'Población.*exclu',
            'Población.*gitan',
            'Población romaní',
            'Poblado.*margina',
            'Pobreza.*gitan',
            'Privación.*libertad.*género',
            'Programa.*Acceder',
            'Programa.*desarrollo.*gitan',
            'Programa.*Promociona',
            'Promoción.*Salud',
            'Protección.*víctima.*género',
            'Protección.*violencia de género',
            'Pueblo.*gitano',
            'Racismo',
            'Racista',
            'Realojo.*gitan',
            'Renta activa.*inserción.*violencia de género',
            'Riesgo.*pobreza',
            'Romafobia',
            'Romaní',
            'Salubridad.*gitan',
            'Salud física.*violencia de género',
            'Salud psicológica.*violencia de género',
            'Saneamiento.*gitan',
            'Segrega.*educación',
            'Segrega.*gitan',
            'Segrega.*sistema educativo',
            'Segrega.*escolar',
            'Segrega.*residencial',
            'Servicio 016',
            'Situación.*exclusión social',
            'Tercera edad.*violencia de género',
            'Víctima.*violencia de género',
            'Violencia de género',
            'Violencia de género.*situación.*irregular',
            'Violencia de género.*situación.*ilegal',
            'Violencia.*pareja',
            'Violencia.*doméstica ',
            'Violencia.*hogar   ',
            'Violencia física.*género',
            'Violencia psicológica.*género',
            'Xenofobia',
            'Xenófob',
        ],
        lastUpdate: now,
    });
    // drogodependencia y conductas adictivas
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'conductas adictivas',
        slug: 'conductas-adictivas',
        description: 'Las personas en situación de drogodependencia, ludopatía u otras conductas adictivas se encuentran habitualmente en riesgo de exclusión social por lo que las medidas de atención, de inserción en la sociedad y de fomento de sus capacidades reducen su situación de vulnerabilidad y fomentan su dignidad como personas.',
        icon1: 'adictivas-01.svg',
        icon2: 'adictivas-02.svg',
        iconb1: 'adictivas-01.svg',
        iconb2: 'adictivas-02.svg',
        words: [
            'Acción.*Europea.*Droga ',
            'Adic.*nueva.*tecnología',
            'Adic.*Internet',
            'Adic.*sustancia',
            'Adic.*juego',
            'Adic.*Internet',
            'Adic.*juego',
            '\\WAED\\W',
            'AED.*droga',
            'Alcohol',
            'Atracón',
            'Botellón',
            'Cannabis',
            'Centro[ s] de día',
            '\\WCICAD\\W',
            'Coaching.*adic',
            'Cocaína',
            'Comunidad.*Terapéutica',
            'Consumo.*alcohol',
            'Consumo.*droga',
            'Consumo.*inhala',
            'Consumo.*recreativo.*drog',
            '\\WCREFAT\\W ',
            'Drododepend.*Cárcel',
            'Drog.*Derecho.*humano',
            'Droga.*Exclu',
            'Droga.*Margina',
            'Droga.*Pobre',
            'Droga.*Prisión',
            'Drogadic.*cárcel',
            'Drogadic.*Exclu',
            'Drogadic.*inmigra',
            'Drogadic.*Integra',
            'Drogadic.*Marginal',
            'Drogadic.*Pobreza',
            'Drogadic.*Prisión',
            'Drogadic.*Reinserción',
            'Drogadic.*género',
            'Drogadic.*violencia de género',
            'Drogadic.*Vulnera',
            'Drogadicción',
            'Drogodepend',
            'Drogodepend.*Exclu',
            'Drogodepend.*inmigra',
            'Drogodepend.*Integra',
            'Drogodepend.*Marginal',
            'Drogodepend.*Pobreza',
            'Drogodepend.*Prisión',
            'Drogodepend.*Reinserción',
            'Drogodepend.*género',
            'Drogodepend.*violencia de género',
            'Drogodepend.*vulnera',
            '\\WEAD\\W',
            'Factor.*prevención',
            'Factor.*riesgo.*drog',
            '\\WFAD\\W',
            'Fondo.*Decomisado',
            'Hepatitis B',
            'Hepatitis C',
            'Heroína',
            'Intercambio.*jeringuilla',
            'Intervención.*precoz',
            'Jeringuilla',
            'Libre.*droga ',
            'Ludopat',
            'Metadona',
            'Observatorio.*Droga',
            'Patología.*dual',
            'Persona.*interna.*drogodepend',
            'Plan Nacional.*Droga',
            'Plataforma.*ONG.*Drogas.*Adicciones',
            'Población.*drogodepend',
            '\\WPODA\\W ',
            'Práctica.*sexual.*riesgo',
            'Prevención.*drog',
            'Prevención.*indicada',
            'Prevención.*selectiva',
            'Prevención.*universal',
            'Reinserción.*drog',
            '\\WRIOD\\W',
            'Sobredosis',
            'Tabaquismo',
            'Tratamiento.*adic',
            'Tratamiento.*drogadic',
            '\\WUNAD\\W',
            '\\WUNGASS\\W',
            'Venopunción',
            'Vía.*parenteral',
            '\\WVIH\\W',
            '\\WVNGOC\\W',
        ],
        lastUpdate: now,
    });
    // población reclusa
    Dicts.insert({
        dictgroup: 'tipi',
        dict: 'población reclusa',
        slug: 'poblacion-reclusa',
        description: 'La Institución Penitenciaria en España está orientada a la reeducación y la reinserción social. No obstante, las problemáticas propias y otras asociadas a este colectivo hacen que estas personas se encuentren en una situación de especial vulnerablilidad en cuanto a su inclusión y bienestar social.',
        icon1: 'reclusa-01.svg',
        icon2: 'reclusa-02.svg',
        iconb1: 'reclusa-01.svg',
        iconb2: 'reclusa-02.svg',
        words: [
            'Administración.*penitenciaria',
            'Administraciones.*penitenciarias',
            '25\\W2.*constitución',
            'Cárcel',
            'Centro.*Inserción.*\bsocial\b',
            'Centro.*Penitenciario',
            'Comunicac.*cárcel',
            'Comunicac.*prisión',
            'Comunicac.*penitenciari ',
            'Condición.*vida.*cárcel',
            'Condiciones.*vida.*cárcel',
            'Condición.*vida.*centro[ s] penitenciario',
            'Condiciones.*vida.*centro[ s] penitenciario',
            'Condición.*vida.*prisión',
            'Condiciones.*vida.*prisión',
            'Condición.*vida.*prisiones',
            'Condiciones.*vida.*prisiones',
            'Consejo.*\bsocial\b.*Penitenciario',
            'Convict',
            'Endurecimiento.*pena',
            'Exconvict',
            'Ex.*convict ',
            'Familia.*intern[oa]',
            'Interno.*especial.*seguimiento ',
            '\\WFIES\\W',
            'Gestión.*penitenciaria',
            'Infraestructura.*penitenciaria',
            'Inserción.*laboral.*exconvict',
            'Inserción.*laboral.*ex.*convict',
            'Trabajo.*exconvict',
            'Trabajo.*ex.*convict',
            'Empleo.*exconvict',
            'Empleo.*ex.*convict',
            'Inserción.*laboral.*pres[oa]',
            'Inserción.*\bsocial\b.*exconvict',
            'Inserción.*\bsocial\b.*ex.*convict',
            'Inserción.*\bsocial\b.*pres[oa]',
            'Inserción.*\bsocial\b.*pres[oa]',
            'Institución.*Penitenciaria',
            'Instituciones.*Penitenciarias',
            'Intern[oa].*centro.*penitenciari',
            'Intern[oa].*cárcel',
            'Interno.*preventivo  ',
            'Juez.*vigilancia.*penitenciaria',
            'Jueces.*vigilancia.*penitenciaria',
            '1\\W1979\\W',
            'Ley.*General.*Penitenciaria',
            'Ley.*Penitenciaria',
            'Libertad.*condicional',
            'Libertad.*provisional',
            'Madre.*centro.*penitenciario',
            'Madre.*cárcel',
            'Masificación.*cárcel',
            'Masificación.*centro.*penitenciario',
            'Masificación.*prisión',
            'Masificación.*prisiones',
            'Medio abierto',
            'Módulo.*respeto',
            '\\WPAIEM\\W',
            'Peculio',
            'Pena.*privativa',
            'Penitenciari',
            'Permiso.*salida',
            'Persona.*interna',
            'Persona.*interna.*drogodepend',
            'Población.*reclusa',
            'Primer grado.*penitenciari',
            'Principio.*constituci.*reinserción',
            'Prisión',
            'Prisiones',
            'Prisión.*permanente.*revisable',
            'Privación.*libertad',
            'Interno.*enfermedad.*mental',
            'Interno.*enfermedades.*mentales',
            'Preso.*enfermedad.*mental',
            'Preso.*enfermedades.*mentales',
            '190\\W1996\\W',
            'Real Decreto\\W190\\W',
            'Reclus[oa]',
            'Reeducación',
            'Reforma.*Código Penal',
            'Reglamento.*Penitenciario ',
            'Reinserción',
            'Resocialización',
            'Salud mental.*centro.*penitenciari',
            'Salud mental.*cárcel',
            'Sanidad penitenciaria',
            'Secretaría General.*Instituciones Penitenciarias',
            'Segundo grado.*tratamiento.*penitenciari',
            'Servicio.*penitenciario',
            'Sistema.*penitenciario',
            'Sobreocupación.*centro.*penitenciari',
            'Sobreocupación.*cárcel',
            'TBC.*cárcel',
            'Tuberculosis.*cárcel',
            'TBC.*prisión',
            'TBC.*prisiones',
            'Tuberculosis.*prisión',
            'Tuberculosis.*prisiones',
            'Tercer grado.*tratamiento.*penitenciari',
            'Trabajo.*beneficio.*comunidad',
            'Traslado.*centro.*penitenciari',
            'Traslado.*cárcel',
            'Tratamiento.*penitenciari',
            'Unidad.*terapéutica.*educ',
            'Vis.*vis',
            'Voluntariado.*centro.*penitenciari',
            'Voluntariado.*cárcel',
            'Voluntariado.*prisión',
            'Voluntariado.*prisiones',
        ],
        lastUpdate: now,
    });

}